---
title: "OrdosporaTemperatureSupportingInformation"
author: "Elizabeth Davenport"
date: "2025-09-12"
output: word_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial stuff, including loading packages and importing data

##loading packages
```{r,message=F,warning=F}
library(here)
library(rstatix)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(ggpubr)
library(lubridate)
library(scales)
library(reshape2)
```

## loading files

```{r,message=F,warning=F}
# Tell R where files are stored
here::i_am("scripts/scripts/OrdosporaTemperatureSupportingInformation.Rmd")

# Load Files
##a <- read_csv(here("data/OP_Temp_Exp.csv"))
a <- read_csv(here("data/OrdosporaTemperatureExperiment.csv"))
pitchertemp <- read_csv(here("data/TemperatureInsidePitcher.csv"))
c <- read_csv(here("data/OP_Temp_AUC_infection_prevalence.csv"))
```

```{r,message=F,warning=F}
## Calculating densities
a$UA_L<-(a$'UA'*a$'Total_Volume')/a$'Volume'
a$UJ_L<-(a$'UJ'*a$'Total_Volume')/a$'Volume'
a$UM_L<-(a$'UM'*a$'Total_Volume')/a$'Volume'
a$OPA_L<-(a$'IA.ordo'*a$'Total_Volume')/a$'Volume'
a$OPJ_L<-(a$'IJ.ordo'*a$'Total_Volume')/a$'Volume'
a$OPM_L<-(a$'IM.ordo'*a$'Total_Volume')/a$'Volume'

a$density<-a$UA_L+a$UJ_L+a$UM_L+a$OPA_L+a$OPJ_L+
  a$OPM_L

a$density<-rowSums(a[,c('UA_L','UJ_L','UM_L','OPA_L','OPJ_L','OPM_L')],na.rm=T)

a$uninfected<-rowSums(a[,c('UA_L','UJ_L','UM_L')],na.rm=T)

##infected host densities
a$OPinfected<-rowSums(a[,c('OPA_L','OPJ_L','OPM_L')],na.rm=T)

a$adults<-rowSums(a[,c('UA_L','OPA_L')],na.rm=T)
a$juveniles<-rowSums(a[,c('UJ_L','OPJ_L')],na.rm=T)
a$males<-rowSums(a[,c('UM_L','OPM_L')],na.rm=T)
a$OPprev<-a$OPinfected/a$density
a$JuvenileRatio <- a$juveniles/a$density
a$females <- rowSums(a[,c('adults','juveniles')],na.rm=T)
a$sexratio <- a$males/a$females

a <- as.data.frame(a)
a$Treatment <- as.factor(a$Treatment)
a$Turnover <- as.factor(a$Turnover)
a$TurnoverID <- as.factor(a$TurnoverID)
```

###Temperature inside DVM treatment pitcher
```{r,message=F,warning=F}
pitchertemp <- data.frame(pitchertemp)
pitchertemp$Date <- as.POSIXct(pitchertemp$Date,format="%m/%d/%Y %H:%M",tz=Sys.timezone())
pitchertemp$Temperature <- as.numeric(pitchertemp$Temperature)
cols2 <- c("Air" = "black","Pitcher"="blue")

pitchertempplot = ggplot() + 
  geom_point(pitchertemp,mapping=aes(x=Date,y=Temperature, color = "Pitcher"), size=1) +
  geom_line(pitchertemp,mapping=aes(x=Date,y=Temperature, color = "Pitcher"), linewidth=1) +
  scale_colour_manual(name="",values = cols2)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black")) +
  scale_y_continuous(limits = c(12, 28), breaks = seq(12, 28, 2))+
  labs(x = "Time (hours)",
       y = (expression(bold("Temperature " ( degree*C))))) +
  theme(axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.title = element_text(face = "bold",size = 12),
        legend.text=element_text(size=10,face="bold"),
        legend.position = "none") + 
  scale_x_datetime(breaks = date_breaks("2 hours"), labels = date_format("%H"))
pitchertempplot
##ggsave("PitcherTemperatureDiurnalCycle.jpg", plot = pitchertempplot, width = 4, height = 4, dpi = 600)
```

##AUC prevalence
```{r,message=F,warning=F}
c <- as.data.frame(c)
c$Treatment <- as.factor(c$Treatment)

cols3 <- c("OP20"= "#F09D00","OP_turnover"= "#A14A10","OPdeltaT"="#0072B2","OPdeltaT_turnover"="#0012A0")
level_order <- c('OP20', 'OP_turnover', 'OPdeltaT', 'OPdeltaT_turnover') 

library(Rmisc)
auc_prev_plot2<-summarySE(data = c, measurevar = "AUC", groupvars = c("Treatment"), na.rm = T)
# the line above summarizes data within treatments and calculates sd, se and ci

infprevauc<- # makes the plot
  ggplot(auc_prev_plot2, aes(x=Treatment, y=AUC, color=Treatment)) + 
  geom_line(position=position_dodge(.2))+
  geom_errorbar(aes(ymin=AUC-se, ymax=AUC+se), width=0, 
                position=position_dodge(.2)) + 
  scale_y_continuous(limits = c(0,27), breaks = seq(0, 25, 5))+
  scale_x_discrete(limits = level_order, labels = c("OP20"="20C", "OP_turnover"= "20C + Turnover", "OPdeltaT"="DVM", "OPdeltaT_turnover"="DVM + Turnover"))+
  ggtitle("") +
  ylab("Area under curve \n(prevalence x days)")+
  xlab("Treatment")+
  geom_point(position=position_dodge(.2), size=3)+
  scale_color_manual(values = cols3, breaks = c("OP20", "OP_turnover", "OPdeltaT", "OPdeltaT_turnover"),labels = c("OP20"="20C", "OP_turnover"= "20C + Turnover", "OPdeltaT"="DVM", "OPdeltaT_turnover"="DVM + Turnover"))+
  theme_classic()+
  theme(axis.text = element_text(size = 8, colour = "black"),
        axis.title.x = element_text(face = "bold",size = 8, colour = "black"),
        axis.title.y = element_text(face = "bold",size = 8, colour = "black"),
        legend.position = "none")+
   annotate(geom="text", x=1, y=25, label="a", size=4,
           color="black")+
  annotate(geom="text", x=2, y=13, label="b", size=4,
           color="black")+
  annotate(geom="text", x=3, y=9.5, label="bc", size=4,
           color="black")+
  annotate(geom="text", x=4, y=5, label="c", size=4,
           color="black")

infprevauc # prints the plot

##ggsave("OP_Temp_AUC_Infection_Prevalence.jpg", infprevauc, height = 4, width = 4, dpi = 600) # saves the plot
```

##AUC prevalence stats
```{r,message=F,warning=F}
aucprevmodel<- aov(AUC ~ Treatment, data = c) ##linear model
summary(aucprevmodel)
##significantly different, F value = 32.49, df = 3, p = p<0.001
TukeyHSD(aucprevmodel)
##significantly different pairwise comparisons: OP20-OP_turnover, OPdeltaT_turnover-OP20, OPdeltaT-OP20, OPdeltaT_turnover-OP_turnover
```

##Prevalence v. Density
```{r,message=F,warning=F}
pd = a %>%
  filter(Day > 48)

pd = pd %>%
  filter(TurnoverID == "OP20"| TurnoverID == "TOP20" | TurnoverID == "OPdeltaT" | TurnoverID == "TOPdeltaT")

colsOP20_v2 <- c("OP.20"= "#F09D00","OP20"= "#F09D00","TOP20"= "#A14A10","OP.deltaT"="#0072B2","TOPdeltaT"="#0012A0","OPdeltaT"="#0072B2")

pdOP = pd %>%
  filter(TurnoverID == "OP20"| TurnoverID == "TOP20")

prevdenOP <- ggplot(data=pdOP, aes(x=OPprev,y=density, group=TurnoverID,
                 color=TurnoverID)) +
  geom_point() +
  geom_smooth(method = "lm", se=TRUE, linewidth=.5)+
  scale_colour_manual(name="",values = colsOP20_v2)+
   stat_cor(aes(color = TurnoverID),method="spearman",label.x = .5)+
  scale_x_continuous(limits = c(-0.05,1.05), breaks = seq(0,1,.25))+
  scale_y_continuous(limits = c(0, 2500),breaks = seq(0,2500,500)) +
 ggtitle("(A)") +
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.text=element_text(size=8,face="bold"),
        legend.position = "bottom",
        legend.title = element_blank())+
  labs(x = ("Infection Prevalence"), y = "Host Density")+guides(color=guide_legend(nrow=1, override.aes=list(fill=NA)))

prevdenOP

pdDVM = pd %>%
  filter(TurnoverID == "OPdeltaT" | TurnoverID == "TOPdeltaT")

prevdenDVM <- ggplot(data=pdDVM, aes(x=OPprev,y=density, group=TurnoverID,
                 color=TurnoverID)) +
  geom_point() +
  geom_smooth(method = "lm", se=TRUE, linewidth=.5)+
  scale_colour_manual(name="",values = colsOP20_v2)+
   stat_cor(aes(color = TurnoverID),method="spearman",label.x = .5)+
  scale_x_continuous(limits = c(-0.05,1.05), breaks = seq(0,1,.25))+
  scale_y_continuous(limits = c(0, 2500),breaks = seq(0,2500,500)) +
 ggtitle("(B)") +
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.text=element_text(size=8,face="bold"),
        legend.position = "bottom",
        legend.title = element_blank())+
  labs(x = ("Infection Prevalence"), y = "Host Density")+guides(color=guide_legend(nrow=1, override.aes=list(fill=NA)))

prevdenDVM

##ggsave(here("figures", "Prev_v_dens_v2.jpg"), prevden, width = 6, height = 4, dpi = 600)


combinedprevdenplots = ggarrange(prevdenOP,prevdenDVM,
                     nrow = 1, ncol = 2, common.legend = FALSE, legend="bottom")
combinedprevdenplots
##ggsave("Combo_Density_v_Prev.jpg", combinedprevdenplots, width = 9, height = 4, dpi = 600)



resPrevDen <- cor.test(pd$OPprev, pd$density, group = TurnoverID, 
                method = "pearson")
resPrevDen

```


##Control densities only
```{r,message=F,warning=F}
C <- as.data.frame(a)

C <- C %>% filter(Treatment == "Control.20"| Treatment == "Control.deltaT")
C_b4 <- C %>% filter(Day < 50)
C_l8tr <- C %>% filter(Day > 48)

C_b4$Treatment <- as.factor(C_b4$Treatment)

C_l8tr$Treatment <- as.factor(C_l8tr$Treatment)
C_l8tr$Turnover <- as.factor(C_l8tr$Turnover)
C_l8tr$TurnoverID <- as.factor(C_l8tr$TurnoverID)

colsC_v2 <- c("Control.20"= "#009E73","C20"= "#009E73","TC20"= "#114A10","Control.deltaT"="#A853F9","TCdeltaT"="purple4","CdeltaT"="#A853F9")

onlyControlv2<- ggplot()+
  geom_smooth(data=C_b4, aes(x=Day, y=density, group=Treatment, color=Treatment), span = 0.4, se=FALSE) +
  geom_point(data=C_b4, aes(x=Day, y=density, group=Treatment, color=Treatment), size =.5, alpha=.5)+
  geom_smooth(data=C_l8tr, aes(x=Day, y=density, group=TurnoverID, color=TurnoverID), span = 0.4, se=FALSE) +
  geom_point(data=C_l8tr, aes(x=Day, y=density, group=TurnoverID, color=TurnoverID), size =.5, alpha=.5)+
  scale_colour_manual(values = colsC_v2, breaks = c('Control.20', 'TC20', 'Control.deltaT', 'TCdeltaT'), 
                      labels = c("20C", "20C + Turnover", "DVM", "DVM + Turnover"))+
  scale_x_continuous(limits = c(0,90), breaks = seq(0,90,10))+
  geom_vline(xintercept = 49)+
  theme_bw()+theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("") +
  labs(y=("Density"), color = ("Treatment"))+
  theme(plot.title = element_text(face = "bold",size = 10),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=8,face="bold"),
        legend.text=element_text(size=6,face="bold"),
        legend.title=element_text(size=8,face="bold"),
        legend.key.width = unit(1.5, 'cm'),
        legend.position = "bottom")+guides(col = guide_legend(nrow = 1, theme = theme(legend.byrow = TRUE)))

onlyControlv2
##ggsave("Control_density_only.jpg", onlyControlv2, width = 6, height = 4, dpi = 600)


```

##All densities
```{r,message=F,warning=F}
allden <- as.data.frame(a)
allden_b4 <- allden %>% filter(Day < 50)
allden_l8tr <- allden %>% filter(Day > 48)

allden_b4$Treatment <- as.factor(allden_b4$Treatment)

allden_l8tr$Treatment <- as.factor(allden_l8tr$Treatment)
allden_l8tr$Turnover <- as.factor(allden_l8tr$Turnover)
allden_l8tr$TurnoverID <- as.factor(allden_l8tr$TurnoverID)

colsallden_v2 <- c("Control.20"= "#009E73","C20"= "#009E73","TC20"= "#114A10","Control.deltaT"="#A853F9","TCdeltaT"="purple4","CdeltaT"="#A853F9",
    "OP.20"= "yellow2","OP20"= "yellow2","TOP20"="yellow4",
    "OP.deltaT"="#F09D00","TOPdeltaT"="#A14A10",
    "OPdeltaT"="#F09D00")

alldensityplot<- ggplot()+
  geom_smooth(data=allden_b4, aes(x=Day, y=density, group=Treatment, color=Treatment), span = 0.4, se=FALSE) +
  geom_point(data=allden_b4, aes(x=Day, y=density, group=Treatment, color=Treatment), size =.5, alpha=.5)+
  geom_smooth(data=allden_l8tr, aes(x=Day, y=density, group=TurnoverID, color=TurnoverID), span = 0.4, se=FALSE) +
  geom_point(data=allden_l8tr, aes(x=Day, y=density, group=TurnoverID, color=TurnoverID), size =.5, alpha=.5)+
  scale_colour_manual(values = colsallden_v2, breaks = c('Control.20', 'TC20', 'Control.deltaT', 'TCdeltaT',
                                                    'OP.20', 'TOP20', 'OP.deltaT', 'TOPdeltaT') , 
                      labels = c("20C", "20C + Turnover", "DVM", "DVM + Turnover",
                                 'OP 20C', 'OP 20C + Turnover', 'OP DVM', 'OP DVM + Turnover'))+
  scale_x_continuous(limits = c(0,90), breaks = seq(0,90,10))+
  geom_vline(xintercept = 49)+
  theme_bw()+theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("") +
  labs(y=("Density"), color = ("Treatment"))+
  theme(plot.title = element_text(face = "bold",size = 10),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=8,face="bold"),
        legend.text=element_text(size=6,face="bold"),
        legend.title=element_text(size=8,face="bold"),
        legend.key.width = unit(1.5, 'cm'),
        legend.position = "bottom")+guides(col = guide_legend(nrow = 2, theme = theme(legend.byrow = TRUE)))

alldensityplot
##ggsave("All_treatment_density.jpg", alldensityplot, width = 8, height = 6, dpi = 600)
```


###Juvenile ratio
```{r,message=F,warning=F}
jratio <- a %>% filter(Day > 48)

# linear model of parasite*temperature*day interaction
juvratio.model<-lm(JuvenileRatio~Parasite*Temperature*Day,data=jratio)
summary(juvratio.model)
anova(juvratio.model)
##significant 3-way interaction (df = 3, F = 3.07, p = 0.029)

jratio20 <- jratio %>% filter(TurnoverID == "C20" | TurnoverID == "OP20" )
# linear model of 20C interaction
juvratio.model20<-lm(JuvenileRatio~Parasite*Day,data=jratio20)
summary(juvratio.model20)
anova(juvratio.model20)
##significant effect of treatment (df = 1, F = 10.12, p = 0.0024)

jratio20T <- jratio %>% filter(TurnoverID == "TC20" | TurnoverID == "TOP20" )
# linear model of 20C+turnover interaction
juvratio.modelT20<-lm(JuvenileRatio~Parasite*Day,data=jratio20T)
summary(juvratio.modelT20)
anova(juvratio.modelT20)
##significant effect of treatment (df = 1, F = 20.24, p < 0.0001) and day (df=1, f = 10.28, p = 0.0022)

jratioDVM <- jratio %>% filter(TurnoverID == "CdeltaT" | TurnoverID == "OPdeltaT" )
# linear model of DVM interaction
juvratio.modelDVM<-lm(JuvenileRatio~Parasite*Day,data=jratioDVM)
summary(juvratio.modelDVM)
anova(juvratio.modelDVM)
##no significant effect of treatment (df = 1, F = 2.35, p =0.13) or day (df=1, f = 1.27, p = 0.27)

jratioDVMT <- jratio %>% filter(TurnoverID == "TCdeltaT" | TurnoverID == "TOPdeltaT" )
# linear model of DVM+turnover interaction
juvratio.modelTDVM<-lm(JuvenileRatio~Parasite*Day,data=jratioDVMT)
summary(juvratio.modelTDVM)
anova(juvratio.modelTDVM)
##significant interaction (df = 1, F = 14.931, p =0.00029)


colsjr <- c("C20"= "#009E73",
              "TC20"= "#114A10",
              "TCdeltaT"="purple4","CdeltaT"="#A853F9",
   "OP20"= "yellow2","TOP20"="yellow4",
    "TOPdeltaT"="#A14A10",
    "OPdeltaT"="#F09D00")


j.ratio.20 <- ggplot() +
  geom_point(data=jratio20, aes(x=Day,y=JuvenileRatio, group=TurnoverID,
                 color=TurnoverID), size=1) +
  geom_smooth(data=jratio20, aes(x=Day,y=JuvenileRatio, group=TurnoverID,
                color=TurnoverID), method = "lm", se=TRUE, linewidth=1)+
  scale_colour_manual(name="",values = colsjr)+
  scale_x_continuous(limits = c(45,90), breaks = seq(45,90,15))+
  scale_y_continuous(limits = c(-0.05, 1.05),breaks = seq(0,1,.25), name="Proportion of juveniles") +
 ggtitle("20C") +
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.text=element_text(size=8,face="bold"),
        legend.position = "none",
        legend.title = element_blank())+
  labs(x = (""))

j.ratio.20

jratio20T <- jratio %>% filter(TurnoverID == "TC20" | TurnoverID == "TOP20" )

j.ratio.20T <- ggplot() +
  geom_point(data=jratio20T, aes(x=Day,y=JuvenileRatio, group=TurnoverID,
                 color=TurnoverID), size=1) +
  geom_smooth(data=jratio20T, aes(x=Day,y=JuvenileRatio, group=TurnoverID,
                color=TurnoverID), method = "lm", se=TRUE, linewidth=1)+
  scale_colour_manual(name="",values = colsjr)+
  scale_x_continuous(limits = c(45,90), breaks = seq(45,90,15))+
  scale_y_continuous(limits = c(-0.05, 1.05),breaks = seq(0,1,.25), name="") +
 ggtitle("20C + Turnover") +
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.text=element_text(size=8,face="bold"),
        legend.position = "none",
        legend.title = element_blank())+
  labs(x = (""))

j.ratio.20T

jratioDVM <- jratio %>% filter(TurnoverID == "CdeltaT" | TurnoverID == "OPdeltaT" )

j.ratio.DVM <- ggplot() +
  geom_point(data=jratioDVM, aes(x=Day,y=JuvenileRatio, group=TurnoverID,
                 color=TurnoverID), size=1) +
  geom_smooth(data=jratioDVM, aes(x=Day,y=JuvenileRatio, group=TurnoverID,
                color=TurnoverID), method = "lm", se=TRUE, linewidth=1)+
  scale_colour_manual(name="",values = colsjr)+
  scale_x_continuous(limits = c(45,90), breaks = seq(45,90,15))+
  scale_y_continuous(limits = c(-0.05, 1.05),breaks = seq(0,1,.25), name="Proportion of juveniles") +
 ggtitle("DVM") +
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.text=element_text(size=8,face="bold"),
        legend.position = "none",
        legend.title = element_blank())+
  labs(x = ("Day"))

j.ratio.DVM


jratioDVMT <- jratio %>% filter(TurnoverID == "TCdeltaT" | TurnoverID == "TOPdeltaT" )

j.ratio.DVMT <- ggplot() +
  geom_point(data=jratioDVMT, aes(x=Day,y=JuvenileRatio, group=TurnoverID,
                 color=TurnoverID), size=1) +
  geom_smooth(data=jratioDVMT, aes(x=Day,y=JuvenileRatio, group=TurnoverID,
                color=TurnoverID), method = "lm", se=TRUE, linewidth=1)+
  scale_colour_manual(name="",values = colsjr)+
  scale_x_continuous(limits = c(45,90), breaks = seq(45,90,15))+
  scale_y_continuous(limits = c(-0.05, 1.05),breaks = seq(0,1,.25), name="") +
 ggtitle("DVM + Turnover") +
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.text=element_text(size=8,face="bold"),
        legend.position = "none",
        legend.title = element_blank())+
  labs(x = ("Day"))

j.ratio.DVMT


j.ratio.all <- ggplot() +
  geom_point(data=jratio, aes(x=Day,y=JuvenileRatio, group=TurnoverID,
                 color=TurnoverID), size=1) +
  geom_smooth(data=jratio, aes(x=Day,y=JuvenileRatio, group=TurnoverID,
                color=TurnoverID), method = "lm", se=TRUE, linewidth=1)+
  scale_colour_manual(name="",values = colsjr, breaks = c('C20','OP20', 'TC20','TOP20', 'CdeltaT','OPdeltaT', 'TCdeltaT', 'TOPdeltaT') , 
                      labels = c("20C",'OP 20C', "20C + Turnover",'OP 20C + Turnover', "DVM",'OP DVM', "DVM + Turnover", 'OP DVM + Turnover'))+
  scale_x_continuous(limits = c(45,90), breaks = seq(45,90,15))+
  scale_y_continuous(limits = c(-0.05, 1.05),breaks = seq(0,1,.25), name="Juvenile Ratio") +
 ggtitle("") +
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.text=element_text(size=8,face="bold"),
        legend.position = "bottom",
        legend.title = element_blank())+
  labs(x = ("Day"))+guides(col = guide_legend(nrow = 2, theme = theme(legend.byrow = TRUE)))+ guides(color = guide_legend(override.aes = list(fill = NA)))

j.ratio.all

##cnames <- c("20C"= "#F09D00","20C + Turnover"= "#A14A10","DVM"="#0072B2","DVM + Turnover"="#0012A0")


blank <- ggplot()+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

```

```{r,message=F,warning=F}
leg <- get_legend(j.ratio.all)

combined.plots_jr = ggarrange(j.ratio.20, j.ratio.20T, j.ratio.DVM, j.ratio.DVMT,
                              ggarrange(blank,leg, nrow = 1, ncol = 2, widths = c(100, .001)),
                     nrow = 3, ncol = 2, widths = c(1,1),heights = c(1,1, .15))
combined.plots_jr

##ggsave("JuvenileRatioCombinedOPTemp.jpg", combined.plots_jr, height = 8, width = 7, dpi = 600) # saves the plot

```


##sex ratio
```{r,message=F,warning=F}
colssr <- c("OP.20"= "#F09D00","OP20"= "#F09D00","TOP20"= "#A14A10","OP.deltaT"="#0072B2","TOPdeltaT"="#0012A0","OPdeltaT"="#0072B2")

sr <- as.data.frame(a)
b4 <- sr %>% filter(Day < 50)
l8tr <- sr %>% filter(Day > 48)

b4 <- b4 %>% filter(Treatment != "Control.20")
b4 <- b4 %>% filter(Treatment != "Control.deltaT")
l8tr <- l8tr %>% filter(Treatment != "Control.20")
l8tr <- l8tr %>% filter(Treatment != "Control.deltaT")


malePlot <- ggplot()+
  geom_smooth(data=b4, aes(x=Day, y=sexratio, group=Treatment, color=Treatment), 
              span = 0.3, se=FALSE) +
  geom_point(data=b4, aes(x=Day, y=sexratio, color=Treatment), size =.5, alpha=.5)+
  geom_smooth(data=l8tr, aes(x=Day, y=sexratio, group=TurnoverID, color=TurnoverID), 
              span = 0.3, se=FALSE) +
  geom_point(data=l8tr, aes(x=Day, y=sexratio, color=TurnoverID), size =.5, alpha=.5)+
  ##geom_smooth(data=b4, aes(x=Day, y=males, group=Treatment, color=Treatment), span = 0.3, se=FALSE) +
  ##geom_point(data=b4, aes(x=Day, y=males, color=Treatment), size =.5, alpha=.5)+
  ##geom_smooth(data=l8tr, aes(x=Day, y=males, group=TurnoverID, color=TurnoverID), span = 0.3, se=FALSE) +
 ## geom_point(data=l8tr, aes(x=Day, y=males, color=TurnoverID), size =.5, alpha=.5)+
  scale_colour_manual(values = colssr, breaks = c('OP20','OPdeltaT','TOP20', 'TOPdeltaT') , 
                      labels = c('OP 20C','OP DVM', 'OP 20C + Turnover', 
                                  'OP DVM + Turnover'))+
  scale_x_continuous(limits = c(0,90), breaks = seq(0,90,10))+
    ##scale_y_continuous(limits = c(0,200), breaks = seq(0,200,50))+
  geom_vline(xintercept = 49)+
  theme_bw()+theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("") +
  labs(y=("Sex ratio"), color = ("Treatment"))+
  theme(plot.title = element_text(face = "bold",size = 10),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=8,face="bold"),
        legend.text=element_text(size=6,face="bold"),
        legend.title=element_text(size=8,face="bold"),
        legend.key.width = unit(1.5, 'cm'),
        legend.position = "bottom")+guides(col = guide_legend(nrow = 2, theme = theme(legend.byrow = TRUE)))

malePlot
##ggsave(here("figures", "Temperature_Pitcher_Exp_sexratio.jpg"), malePlot, width = 6, height = 4, dpi = 600)
```
 
 
###GAM for Daphnia density before turnover
```{r,message=F,warning=F}
data_past49<- a[a$Day>49,] 
data_past49$Treatment<- as.factor(data_past49$Treatment)
data_before49<- a[a$Day<49,] 
data_before49$Treatment<- as.factor(data_before49$Treatment)

library(mgcv)
library(Rmisc)
library(emmeans)

only.Cb4 = data_before49 %>%
  filter(Treatment =="Control.20" | Treatment == "Control.deltaT")


# GAM model on Daphnia density before turnover
# interaction between treatment and day and separate smoothers for each treatment

dens_gam1 <- gam(density ~ Treatment*Day + 
             s(Day, by = as.numeric(Treatment == "Control.20"), k = 4) + 
             s(Day, by = as.numeric(Treatment == "Control.deltaT"), k = 4), 
           data = only.Cb4)

summary(dens_gam1)
anova(dens_gam1)
#significant interactions between day and smoothers


# Pairwise comparisons and contrasts between the models accros time
EM_dens_gam1 <- emmeans(dens_gam1, ~ Treatment | Day, at = list(Day = seq(0, 48, 
                                                                        by = 1)))
contrast(EM_dens_gam1, method = "pairwise", adjust = "bonferroni") # pairwise contrast comparison with bonferroni correction
contrasts_dens_gam1<-contrast(EM_dens_gam1, method = "pairwise", adjust = "bonferroni")
# Exporting post-hoc comparisons into .csv files
pairwise_comparisons_dens_gam1 <- as.data.frame(summary(contrasts_dens_gam1))
##write.csv(pairwise_comparisons_dens_gam1, file = "pairwise_comparisons_control_dens_gam_0_48.csv", row.names = FALSE)
##write.csv(EM_dens_gam1, file = "EM_dens_control_gam_0_48.csv", row.names = FALSE)

# GAM model after turnover
# interaction between treatment and day and separate smoothers for each treatment

```


###GAM for Daphnia density after turnover
```{r,message=F,warning=F}

# interaction between treatment and day and separate smoothers for each treatment
data_past49$TurnoverID<-as.factor(data_past49$TurnoverID)
only.Caf = data_past49 %>%
  filter(Treatment =="Control.20" | Treatment == "Control.deltaT")

dens_gam2 <- gam(density ~ TurnoverID*Day + 
             s(Day, by = as.numeric(TurnoverID == "TC20"), k=4) + 
               s(Day, by = as.numeric(TurnoverID == "TCdeltaT"), k=4)+
             s(Day, by = as.numeric(TurnoverID == "C20"), k=4) + 
             s(Day, by = as.numeric(TurnoverID == "CdeltaT"), k=4), 
           data = only.Caf)

summary(dens_gam2)
anova(dens_gam2)
#significant interactions between day and smoothers


# Pairwise comparisons and contrasts between the models accros time
EM_dens_gam2 <- emmeans(dens_gam2, ~ TurnoverID | Day, at = list(Day = seq(49, 84, 
                                                                        by = 1)))
contrast(EM_dens_gam2, method = "pairwise", adjust = "bonferroni") # pairwise contrast comparison with bonferroni correction
contrasts_dens_gam2<-contrast(EM_dens_gam2, method = "pairwise", adjust = "bonferroni")
# Exporting post-hoc comparisons into .csv files
pairwise_comparisons_dens_gam2 <- as.data.frame(summary(contrasts_dens_gam2))
##write.csv(pairwise_comparisons_dens_gam2, file = "pairwise_comparisons_Control_gam_49_84_afterT.csv", row.names = FALSE)
##write.csv(EM_dens_gam2, file = "EM_Control_gam_49_84_afterT.csv", row.names = FALSE)
```


 
